### ISSUE TITLE
Реклама Chrome на странице Добавить клиента

### ISSUE THREAD

**Issue by TurangaLila90** [nochlezhka/mks#35]
branch update-versions https://github.com/nochlezhka/mks/commit/53e6c97636fdeab7f9bce7586bee9e79dcf7909b

## Шаги воспроизведения

1. Клиенты >> Добавить клиента

Ожидаемый результат: реклама отсутсвует
Фактический результат: реклама Chrome на странице Добавить клиента

### Окружение

macOS Version 12.4
Google Chome Version 102.0.5005.61

Cкриншот: https://disk.yandex.ru/i/7mf7I8LGACh3TQ

**Comment by satamas** [comment]
Это происходит если не загружаются ассеты. У меня локально с собранным образом приложения это не воспроизводится.
