### ISSUE TITLE
Не отображается картинка МКС

### ISSUE THREAD

**Issue by TurangaLila90** [nochlezhka/mks#36]
branch update-versions https://github.com/nochlezhka/mks/commit/53e6c97636fdeab7f9bce7586bee9e79dcf7909b

## Шаги воспроизведения

1. Страница Вход

Ожидаемый результат: Отображается картинка МКС
Фактический результат: Картинка не отображается

2. Ввести корректное Имя пользователя и Пароль
3. Нажать на кнопку Вход

Ожидаемый результат: В левом углу отображается картинка МКС
Фактический результат: Картинка не отображается

### Окружение

macOS Version 12.4
Google Chome Version 102.0.5005.61

Cкриншот 1: https://disk.yandex.ru/i/zM-DECEMAFZgTg
Скриншот 2: https://disk.yandex.ru/i/yB8tmj4shHa3nA

**Comment by satamas** [comment]
Это происходит если не загружаются ассеты. У меня локально с собранным образом приложения это не воспроизводится.
