### ISSUE TITLE
Отсутстсвует выпадающий список Отделения* (или Регионы) на странице создания нового пользователя

### ISSUE THREAD

**Issue by TurangaLila90** [nochlezhka/mks#40]
В разделе Настройки есть Регионы, которые должны отражаться в выпадающем списке Отделения*

## Шаги воспроизведения

1. Личный кабинет > Мой профиль
2. Действия > Добавить

Ожидаемый результат: присутствует обязательное к заполнению выпадающий список Отделения* (или Регионы) 
Фактический результат: отсутствует

### Окружение:

macOS Version 12.4
Google Chome Version 102.0.5005.61

Скриншот: https://disk.yandex.ru/i/YdHquMbOURAHNA

**Comment by satamas** [comment]
Судя по коду такого не предполагается в принципе. Там есть отдельное поле lastRegistrationDistrict, которое привязано к региону и, возможно, оно где-то используется, да и то не факт
