### ISSUE TITLE
Отчеты - Можно создать отчет без заполнения обязательных полей

### ISSUE THREAD

**Issue by Alena-Stavrova** [nochlezhka/mks#47]
### Шаги воспроизведения
Поля тип (выпадающий список с вариантом по умолчанию), дата начала и дата окончания являются обязательными.

1. Личный кабинет > Отчеты
2. Кнопка "Сгенерировать"

Ожидаемый результат: система не позволяет сгенерировать отчет, подсказка о необходимости добавить даты начала и окончания
Фактический результат: отчет готов к загрузке в папку

### Окружение
Windows 10 Домашняя
Google Chrome Version 103.0.5060.134

[пустой отчет.webm](https://user-images.githubusercontent.com/33433876/181915942-289c2e51-33c1-44e4-86da-4297d219656b.webm)

**Comment by ebulgakova** [comment]
не баг
